[project]
name = "comparable"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs~=3.0.0",
    "scikit-learn>=1.8.0",
    "tensorflow==2.19.1",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]